# Конфигурация плагина Nether_Damage
# Максимальная высота Y, выше которой наносится урон
maxY: 127
# Сила урона (2.0 = 1 сердце)
damage: 2.0
# Сообщение игроку при получении урона в Незере
hotMessage: "§cЗдесь очень горячо!"
